### PR TITLE
feat: personal contact group management

### PR DESCRIPTION
**Pull request by Laurin-W**
Hey @srosset81 this is still work in progress in parts (styling, components to select tags & groups, some cleanup) but I thought you might want to take a first look :)

First I added a new container.
Then I added react admin components for managing groups and their members (some styling left to do).
Right now I'm working on the two components to select groups (tags) for a user and selecting users with the help of groups.

### CODE REVIEW

**Comment by Laurin-W** [comment]
Hey @srosset81 the feature is all ready for a review now from my side :)

**Comment by Laurin-W** [comment]
Moved the tag and resource select component to semapps repo, see PR https://github.com/assemblee-virtuelle/semapps/pull/1146

**Review by srosset81 — COMMENTED** [review]
A few quick comments

**Comment by Laurin-W** [comment]
Thanks for the comments, I addressed them in https://github.com/assemblee-virtuelle/activitypods/pull/77/commits/f6234d4ab9ccb59557cacd2656ba4ce91466ff6d.

**Comment by srosset81** [comment]
Merging everything into the `next` branch...

**Pull request merged**
